In [1]:
import tensorflow
import numpy as np
import os
import time 


2023-03-14 18:39:25.484688: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-14 18:39:25.585493: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-03-14 18:39:25.809858: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-03-14 18:39:25.811299: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-14 18:39:28.574618: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [2]:
text=open('kafka.txt','r').read()


In [3]:
import re                                

def clean_text(text):
  text = re.sub(r',', '', text)
  text = re.sub(r'\'', '',  text)
  text = re.sub(r'\"', '', text)
  text = re.sub(r'\(', '', text)
  text = re.sub(r'\)', '', text)
  text = re.sub(r'\n', '', text)
  text = re.sub(r'“', '', text)
  text = re.sub(r'”', '', text)
  text = re.sub(r'’', '', text)
  text = re.sub(r'\?', '', text)
  text = re.sub(r';', '', text)
  text = re.sub(r':', '', text)
  text = re.sub(r'\-', '', text)

  return text

In [4]:
clean_text(text)
print(text[:250])


One morning, when Gregor Samsa woke from troubled dreams, he found
himself transformed in his bed into a horrible vermin. He lay on his
armour-like back, and if he lifted his head a little he could see his
brown belly, slightly domed and divided by a


In [5]:
lower_data = text.lower()           

split_data = lower_data.splitlines()      


final = ''                                

for line in split_data:
  line = clean_text(line)
  final += line



In [6]:

final_data=final.split('.')
print(final_data[:1])

['one morning when gregor samsa woke from troubled dreams he foundhimself transformed in his bed into a horrible vermin']


In [8]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


max_vocab = 1000000
tokenizer = Tokenizer(num_words=max_vocab)
tokenizer.fit_on_texts(final_data)


In [9]:
word2idx = tokenizer.word_index
print(len(word2idx))
print(word2idx)
vocab_size = len(word2idx) + 1        # Adding 1 to the vocab_size because the index starts from 1 not 0. This will make it uniform when using it further
print(vocab_size)

3814
{'the': 1, 'to': 2, 'and': 3, 'he': 4, 'his': 5, 'of': 6, 'was': 7, 'in': 8, 'had': 9, 'it': 10, 'that': 11, 'a': 12, 'as': 13, 'gregor': 14, 'him': 15, 'with': 16, 'she': 17, 'would': 18, 'her': 19, 'not': 20, 'at': 21, 'but': 22, 'for': 23, 'on': 24, 'they': 25, 'room': 26, 'all': 27, 'be': 28, 'out': 29, 'from': 30, 'could': 31, 'if': 32, 'have': 33, 'there': 34, 'so': 35, 'been': 36, 'father': 37, 'now': 38, 'gregors': 39, 'sister': 40, 'this': 41, 'door': 42, 'back': 43, 'then': 44, 'himself': 45, 'up': 46, 'into': 47, 'even': 48, 'mother': 49, 'when': 50, 'did': 51, 'their': 52, 'were': 53, 'what': 54, 'more': 55, 'way': 56, 'about': 57, 'them': 58, 'i': 59, 'only': 60, 'said': 61, 'than': 62, 'no': 63, 'by': 64, 'one': 65, 'time': 66, 'little': 67, 'just': 68, 'you': 69, 'get': 70, 'any': 71, 'do': 72, 'or': 73, 'first': 74, 'see': 75, 'made': 76, 'before': 77, 'some': 78, 'after': 79, 'head': 80, 'go': 81, 'still': 82, 'other': 83, 'again': 84, 'while': 85, 'samsa': 86, 'm

In [10]:
input_seq = []

for line in final_data:
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    n_gram_seq = token_list[:i+1]
    input_seq.append(n_gram_seq)

print(input_seq)

[[65, 150], [65, 150, 50], [65, 150, 50, 14], [65, 150, 50, 14, 86], [65, 150, 50, 14, 86, 860], [65, 150, 50, 14, 86, 860, 30], [65, 150, 50, 14, 86, 860, 30, 1290], [65, 150, 50, 14, 86, 860, 30, 1290, 861], [65, 150, 50, 14, 86, 860, 30, 1290, 861, 4], [65, 150, 50, 14, 86, 860, 30, 1290, 861, 4, 1291], [65, 150, 50, 14, 86, 860, 30, 1290, 861, 4, 1291, 1292], [65, 150, 50, 14, 86, 860, 30, 1290, 861, 4, 1291, 1292, 8], [65, 150, 50, 14, 86, 860, 30, 1290, 861, 4, 1291, 1292, 8, 5], [65, 150, 50, 14, 86, 860, 30, 1290, 861, 4, 1291, 1292, 8, 5, 108], [65, 150, 50, 14, 86, 860, 30, 1290, 861, 4, 1291, 1292, 8, 5, 108, 47], [65, 150, 50, 14, 86, 860, 30, 1290, 861, 4, 1291, 1292, 8, 5, 108, 47, 12], [65, 150, 50, 14, 86, 860, 30, 1290, 861, 4, 1291, 1292, 8, 5, 108, 47, 12, 862], [65, 150, 50, 14, 86, 860, 30, 1290, 861, 4, 1291, 1292, 8, 5, 108, 47, 12, 862, 1293], [4, 138], [4, 138, 24], [4, 138, 24, 1294], [4, 138, 24, 1294, 43], [4, 138, 24, 1294, 43, 3], [4, 138, 24, 1294, 43, 3,

In [11]:
max_seq_length = max(len(x) for x in input_seq)
print(max_seq_length)


input_seq = np.array(pad_sequences(input_seq, maxlen=max_seq_length, padding='pre'))
print(input_seq)


xs = input_seq[:, :-1]        
labels = input_seq[:, -1]
print("xs: ",xs)
print("labels:",labels)


143
[[   0    0    0 ...    0   65  150]
 [   0    0    0 ...   65  150   50]
 [   0    0    0 ...  150   50   14]
 ...
 [   0    0    0 ... 1027   29   19]
 [   0    0    0 ...   29   19  855]
 [   0    0    0 ...   19  855  128]]
xs:  [[   0    0    0 ...    0    0   65]
 [   0    0    0 ...    0   65  150]
 [   0    0    0 ...   65  150   50]
 ...
 [   0    0    0 ...    3 1027   29]
 [   0    0    0 ... 1027   29   19]
 [   0    0    0 ...   29   19  855]]
labels: [150  50  14 ...  19 855 128]


In [12]:
from tensorflow.keras.utils import to_categorical

ys = to_categorical(labels, num_classes=vocab_size)
print(ys)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
from tensorflow.keras.layers import Input, Dense, Embedding, LSTM, Dropout, Bidirectional, GlobalMaxPooling1D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential

In [14]:
i = Input(shape=(max_seq_length - 1, ))                           # using 1 less value becasuse we are preserving the last value for predicted word 
x = Embedding(vocab_size, 124)(i)
x = Dropout(0.2)(x)
x = LSTM(520, return_sequences=True)(x)
x = Bidirectional(layer=LSTM(340, return_sequences=True))(x)
x = GlobalMaxPooling1D()(x)
x = Dense(1024, activation='relu')(x)
x = Dense(vocab_size, activation='softmax')(x)

2023-03-14 18:39:34.148502: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-03-14 18:39:34.152814: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-03-14 18:39:34.155837: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

In [15]:
model = Model(i,x)

In [16]:
model.compile(optimizer=Adam(lr=0.001),
              loss = 'categorical_crossentropy',
              metrics=['accuracy'])


In [21]:
r = model.fit(xs,ys,epochs=1)

2023-03-14 15:04:46.691313: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-03-14 15:04:46.695993: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-03-14 15:04:46.699856: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

695/695 [==============================] - 885s 1s/step - loss: 6.7388 - accuracy: 0.0471


In [23]:
model.save('poem_generator.h5')